buildscript {
    repositories {
        mavenCentral()
        maven { url 'https://plugins.gradle.org/m2/' }
    }
}

allprojects {
    version = '1.0'
    ext {
        gdxVersion = '1.12.1'
    }

    repositories {
        mavenCentral()
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
        maven { url 'https://oss.sonatype.org/content/repositories/releases/' }
    }
}

project(':core') {
    apply plugin: 'java-library'

    dependencies {
        api "com.badlogicgames.gdx:gdx:$gdxVersion"
    }
}

project(':desktop') {
    apply plugin: 'java'

    dependencies {
        implementation project(':core')
        implementation "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
        implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
    }
}
